### PR TITLE
All workday

### PR DESCRIPTION
**Pull request by TFM110**
I am no programmer but hopefully this works

### CODE REVIEW

**Comment by GregoryConrad** [comment]
hi 👋 

Two questions:
- I’m guessing the URL of WPI’s workday instance changed? (I no longer go to WPI)
- Did you test this locally in chrome via loading the unpacked extension?


Thx

**Comment by TFM110** [comment]
1. Idk. I don't go to WPI but if I want to use this personal, my college's workday uses www
2. No. I don't use chrome, and I'm not a programmer, I was just using my context clues and seeing why it wasn't working on Firefox, and the wd5. is what made me think that.

**Comment by GregoryConrad** [comment]
It looks like WPI still uses `wd5.workday.com`.

If you modified this PR to remove the `wd5` instead of replacing it with `www` I think that would be ok; it _may_ work on all workday.com domains then.

**Comment by TFM110** [comment]
Again, I'm not a programmer, I just look at what I think could fix something. I assume this will work but I don't know and I haven't tested. I'm to close this PR and forget about it since I can't test it

**Comment by GregoryConrad** [comment]
Ahh, well thanks for taking the time to submit this but if you haven’t tested it for your school’s workday then I’m going to go ahead and close this (since it’d broaden the scope of web permissions, which I’d prefer not to do unless it’s confirmed that doing so would work)

**Pull request closed without merging**
